name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build project
        run: |
          yarn build

      - name: Upload generated template
        uses: actions/upload-artifact@v4
        id: upload-generated-template
        with:
            name: template-output
            path: dist

      - uses: actions/checkout@v4
        with:
          repository: 'danswater/danswater.github.io'
          ref: 'master'
          token:  ${{ secrets.TEMPLATE_OUTPUT_REPO_TOKEN }}

      - name: Download generated template
        uses: actions/download-artifact@v4
        with:
            name: template-output


      - uses: pixta-dev/repository-mirroring-action@v1
        with:
            target_repo_url:
                git@github.com:danswater/danswater.github.io.git
            ssh_private_key:
                ${{ secrets.SSH_PRIVATE_KEY }}

